import page from "../dist/main.js"
export default function about(){

    const mainDiv = document.createElement("div")
    mainDiv.className = "mainDiv"
    mainDiv.id = "aboutUsMainDiv"
    page.appendChild(mainDiv)
    
    const aboutPara = document.createElement("p")
    aboutPara.className = 'about-para'
    aboutPara.innerText = `Welcome to Steak Town, the legendary haven for meat lovers and connoisseurs of exquisite dining experiences. At Steak Town, we take pride in our rich history, spanning over a century, and our unwavering commitment to serving the finest cuts of beef and providing exceptional hospitality to our esteemed patrons. Our story begins in the late 1800s, when the adventurous entrepreneur, Samuel Johnson, embarked on a journey to establish a steakhouse that would redefine the way people savored their favorite meat. \n\n
    Samuel Johnson, fondly known as "Sizzling Sam" among his peers, was a visionary with an insatiable passion for culinary excellence. Armed with a secret family recipe for the perfect steak seasoning, he set up the first-ever Steak Town restaurant in the heart of a bustling city. From the very beginning, Steak Town gained a reputation for serving succulent, mouthwatering steaks cooked to perfection, earning it the title of 'The Temple of Steaks.' \n\n
    As decades passed, the Johnson family's commitment to maintaining the highest standards never wavered. The next generation, led by the charismatic and innovative chef, William Johnson, introduced new cuts and cooking techniques that solidified Steak Town's position as a culinary landmark. Guests from far and wide flocked to the restaurant, drawn not only by the delicious steaks but also by the warm, welcoming ambiance and the personalized service that became the trademark of Steak Town. \n\n
    In the mid-20th century, under the guidance of William's daughter, Elizabeth Johnson, Steak Town underwent a major expansion, transforming into a sophisticated and elegant dining establishment. Elizabeth's refined taste in interior design elevated the restaurant's aesthetics, making it a favorite spot for social gatherings and special occasions. To this day, the exquisite chandeliers and classic decor in Steak Town pay homage to Elizabeth's timeless style. \n\n
    As the years passed, Steak Town continued to thrive, attracting a diverse clientele, including celebrities, politicians, and discerning food critics. The family's dedication to sourcing the finest ingredients, the most tender and marbled cuts of beef, and maintaining their closely guarded seasoning recipe ensured that every visit to Steak Town was a memorable experience, one that lingered in the hearts of guests for a lifetime. \n\n
    In the 21st century, the Johnson family's tradition lives on, carried forward by Chef Michael Johnson, a master of his craft. Chef Michael continues to innovate while staying true to the time-tested principles that have defined Steak Town for generations. Under his watchful eye, the restaurant expanded its menu to include a wider array of cuts and even introduced delectable plant-based options, ensuring that all guests can find something to tantalize their taste buds. \n\n
    Beyond the culinary delights, Steak Town's commitment to giving back to the community has remained a cornerstone of its philosophy. Through various charity events, scholarships, and partnerships with local farmers, Steak Town is more than just a restaurant; it's a pillar of support and positivity in the city. \n\n
    Today, as we welcome you to Steak Town, we invite you to savor not just the extraordinary flavors of our steaks but also the essence of our rich history and the warmth of our hospitality. From 'Sizzling Sam' to Chef Michael, each generation has left an indelible mark on the legacy of Steak Town, and we are honored to be part of your dining memories. Join us as we continue to serve the finest steaks and create unforgettable experiences, for you are not just guests; you are part of the Steak Town family. Cheers to great food, cherished moments, and a journey that spans generations. Welcome to Steak Town!`
    mainDiv.appendChild(aboutPara)

}